// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcM_HnxM1WVKPS9l75yDShv4CZz5sl1UI',
    appId: '1:1017148209250:web:b89d78a346e38e85d8793b',
    messagingSenderId: '1017148209250',
    projectId: 'ai-flashcards-eea54',
    authDomain: 'ai-flashcards-eea54.firebaseapp.com',
    storageBucket: 'ai-flashcards-eea54.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKti3Cm2mwRkQujyc-uTPbty-cb1-9GUo',
    appId: '1:1017148209250:android:3a52a1b054208f87d8793b',
    messagingSenderId: '1017148209250',
    projectId: 'ai-flashcards-eea54',
    storageBucket: 'ai-flashcards-eea54.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5zo0MOeGbktUYJtOpmg4PJWMv-U5Nz4s',
    appId: '1:1017148209250:ios:f745c2fc14aae321d8793b',
    messagingSenderId: '1017148209250',
    projectId: 'ai-flashcards-eea54',
    storageBucket: 'ai-flashcards-eea54.firebasestorage.app',
    iosBundleId: 'com.example.aiFlashcards',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5zo0MOeGbktUYJtOpmg4PJWMv-U5Nz4s',
    appId: '1:1017148209250:ios:f745c2fc14aae321d8793b',
    messagingSenderId: '1017148209250',
    projectId: 'ai-flashcards-eea54',
    storageBucket: 'ai-flashcards-eea54.firebasestorage.app',
    iosBundleId: 'com.example.aiFlashcards',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcM_HnxM1WVKPS9l75yDShv4CZz5sl1UI',
    appId: '1:1017148209250:web:13d98404c9fd0c97d8793b',
    messagingSenderId: '1017148209250',
    projectId: 'ai-flashcards-eea54',
    authDomain: 'ai-flashcards-eea54.firebaseapp.com',
    storageBucket: 'ai-flashcards-eea54.firebasestorage.app',
  );
}
